# Configuration settings for the minute pipeline
# Paths (unless absolute) are relative to the directory in which snakemake is run.

# Path to a reference FASTA file (may be gzip-compressed)
# with a matching Bowtie2 index in the same location
reference_fasta: "ref.fa.gz"

# Path to a BED file listing the regions to be excluded
blacklist_bed: "blacklist.bed"

# Chromosome lengths file (.chrom.sizes or .genome)
chrom_sizes: "ref.chrom.sizes"

# Effective genome size
genome_size: 3700000

# Length of the 5' UMI
umi_length: 6

# Fragment length (insert size)
fragment_size: 150
