channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - python
  # - importlib-metadata   # [py<38]
  - ruamel.yaml
  - snakemake-minimal >= 7.22.0
  # Explicit openjdk dependency should not be needed - remove when Picard is bumped to 3.0.1 or later
  - openjdk >= 17.0.0
  - samtools >=1.13
  - cutadapt >=3.7
  # bowtie2 2.5.2 crashes on the tests
  - bowtie2 =2.5.1
  - je-suite >=2.0.RC
  - igvtools >=2.5.3
  - deeptools >=3.5.0
  - picard >=2.26.0
  - fastqc >=0.11.9
  - bedtools >=2.30.0
  - multiqc >=1.13
  - xopen >=1.2.0
  - sra-tools >=2.11.0
  - r-base >=4.0.0
  - r-ggplot2 >=3.3.0
  - r-dplyr >=1.0.0
