channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - snakemake-minimal
  - samtools
  - cutadapt
  - bowtie2
  - je-suite
  - igvtools
  - deeptools
  - picard
  - umi_tools
  - fastqc
  - bedtools
  - multiqc
