channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - python
  # - importlib-metadata   # [py<38]
  - ruamel.yaml
  - snakemake-minimal >=6.9.0
  - samtools >=1.13
  - cutadapt >=3.7
  - bowtie2 >=2.4.4
  - je-suite >=2.0.RC
  - igvtools >=2.5.3
  - deeptools >=3.5.0
  - picard >=2.26.0
  - fastqc >=0.11.9
  - bedtools >=2.30.0
  # MultiQC 1.12 ongoing issue with custom_content module
  # https://github.com/ewels/MultiQC/issues/1645
  - multiqc =1.11
  - xopen >=1.2.0
  - sra-tools >=2.11.0
  - r-base >=4.0.0
  - r-ggplot2 >=3.3.0
  - r-dplyr >=1.0.0
