site_name: minute
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Installation: install.md
  - User guide: guide.md
  - Reference: reference.md
  - GitHub repository: https://github.com/elsasserlab/minute

markdown_extensions:
  - admonition