title: "Minute report"
subtitle: ""
intro_text: ""

run_modules:
  - fastqc
  - cutadapt
  - custom_content

module_order:
  - fastqc:
      name: "FastQC on raw reads"
      anchor: "fastqc-raw"
      target: ""
      info: "FastQC results on raw reads"
  - cutadapt:
      name: "Cutadapt"
      anchor: "cutadapt"
      target: ""
      info: "This step removes adapters from reads that no longer have UMIs"
      path_filters:
        - "*.trimmed.log"

custom_data:
  scalinginfo:
    file_format: "tsv"
    section_name: "Scaling factors"

sp:
  scalinginfo:
    fn: "scalinginfo.txt"
