title: "Minute report"
subtitle: ""
intro_text: ""
show_analysis_paths: False
skip_generalstats: true

run_modules:
  - fastqc
  - cutadapt
  - custom_content
  - bowtie2
  - picard

module_order:
  - fastqc:
      name: "FastQC on raw reads"
      anchor: "fastqc-raw"
      target: ""
      info: "FastQC results on raw reads"
  - cutadapt:
      name: "Cutadapt"
      anchor: "cutadapt"
      target: ""
      info: "This step removes adapters from reads that no longer have UMIs"
      path_filters:
        - "*.trimmed.log"
  - bowtie2:
      name: "Bowtie 2 read mapping"
      anchor: "bowtie2"
      target: ""
      info: "Read mapping of demultiplexed reads with Bowtie2"
      path_filters:
        - "log/4-mapped/*.log"
  - picard:
      path_filters:
        - "*.metrics"

custom_data:
  scalinginfo:
    file_format: "tsv"
    section_name: "Scaling factors"
  summary:
    file_format: "tsv"
    section_name: "Statistics summary"

sp:
  scalinginfo:
    fn: "scalinginfo.txt"
  summary:
    fn: "stats_summary.txt"
