title: "Minute report"
subtitle: ""
intro_text: ""
show_analysis_paths: False
skip_generalstats: true
ignore_images: false

run_modules:
  - fastqc
  - cutadapt
  - custom_content
  - bowtie2
  - samtools
  - picard
  - deeptools

module_order:
  - fastqc:
      name: "FastQC on raw reads"
      anchor: "fastqc-raw"
      target: ""
      info: "FastQC results on raw reads"
  - cutadapt:
      name: "Cutadapt"
      anchor: "cutadapt"
      target: ""
      info: "This step removes adapters from reads that no longer have UMIs"
      path_filters:
        - "*.trimmed.log"
  - bowtie2:
      name: "Bowtie 2 read mapping"
      anchor: "bowtie2"
      target: ""
      info: "Read mapping of demultiplexed reads with Bowtie2"
      path_filters:
        - "log/4-mapped/*.log"
  - samtools:
      name: "Samtools stats"
      anchor: "samtools"
      target: ""
      info: "Extra statistics on final BAM files"
      path_filters:
        - "stats/final/*idxstats.txt"
        - "stats/final/*flagstat.txt"
  - picard:
      path_filters:
        - "*.metrics"
        - "*.insertsizes.txt"
  - deeptools:
      path_filters:
        - "stats/final/*fingerprint.log"
        - "stats/final/*fingerprint.metrics"

custom_data:
  scalinginfo:
    file_format: "tsv"
    section_name: "Scaling factors"
  summary:
    file_format: "tsv"
    section_name: "Statistics summary"
  groupedscaling:
    section_name: "Minute scaled read stats"
  replicatescaling:
    section_name: "Minute scaled read stats - replicates only"

sp:
  scalinginfo:
    fn: "scalinginfo.txt"
  summary:
    fn: "stats_summary.txt"
  groupedscaling:
    fn: "grouped_scaling_barplot.png"
  replicatescaling:
    fn: "scaling_barplot.png"


table_cond_formatting_rules:
  percent_duplication:
      pass:
        - lt: 0.1
      warn:
        - gt: 0.1
      fail:
        - gt: 0.25
  insert_size:
        pass:
          - gt: 130
        warn:
          - lt: 130
        fail:
          - lt: 100
