name: CI

on: [push]

jobs:
  run:
    name: Run pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
            micromamba-version: '1.3.1-0'
            environment-file: environment.yml
            environment-name: testenv
            create-args: pytest
            init-shell: bash
            cache-environment: true
      - name: Install pipeline
        shell: bash -el {0}
        run: pip install .
      - name: Run tests
        shell: bash -el {0}
        run: ./test.sh
