name: CI

on: [push, pull_request]

jobs:
  run:
    name: Run pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Conda environment
        run: |
          conda env create --quiet -n testenv -f environment.yml
      - name: Download test dataset
        run: |
          wget https://export.uppmax.uu.se/uppstore2018208/minute-testdata/minute-testdata-0.2.tar.gz
          tar xf minute-testdata-0.2.tar.gz
      - name: Run pipeline
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          ./test.sh
